title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Abhishek Das

domain: "vivektalks.v1vek.com"
baseurl: ""

twitter_username: vivek_kumar
twitter_hashtag: machinelearning
github_username: v1vek
github_repo: vivektalks

markdown: kramdown
ga_id: UA-36274081-2

theme: jekyll-theme-leap-day
